package com.korrali.eudirp.presentation;

import com.nimbusds.jose.jwk.ECKey;

/**
 * A signed OpenID4VP authorization Request Object (RFC 9101 JAR) ready to be delivered to a
 * wallet, plus the parameters needed alongside it to build the request URI / QR payload.
 *
 * <p>{@code responseEncryptionKey} is only present when {@link #responseMode()} is
 * {@link ResponseMode#DIRECT_POST_JWT} — it's the full key pair (public <em>and</em> private),
 * generated by {@link PresentationRequestBuilder}, needed to decrypt the wallet's encrypted
 * response later via {@link AuthorizationResponse#fromDirectPostJwt}. Callers must keep this
 * server-side only — the request itself only ever exposes the public half, via
 * {@code client_metadata.jwks}.
 */
public record SignedPresentationRequest(
        String requestObjectJwt,
        String clientId,
        String nonce,
        String state,
        String responseUri,
        ResponseMode responseMode,
        ECKey responseEncryptionKey
) {
}
